### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Alemax067** [feizc/IEA#1]
(E:\condaenvs\IEA) PS E:\mycode\IEA-main> python service_img2img.py
Traceback (most recent call last):
  File "service_img2img.py", line 14, in <module>
    from diffusers import StableDiffusionLongPromptWeightingPipeline, EulerDiscreteScheduler
ImportError: cannot import name 'StableDiffusionLongPromptWeightingPipeline' from 'diffusers'

**Comment by feizc** [comment]
Update the version of diffusers package can solve the problem :)
